### ISSUE TITLE
PCC Cutoff 

### ISSUE THREAD

**Issue by Zhanglesolanin** [pFindStudio/pDeep#1]
Hello，

First of all, I want to thank pFinders for providing so many convenient and practical software. You are really a great team.

Recently, I want to use the pDeep2 software to perform some verification on some suspected PSMs in our previous identification results. I encountered some problems in the process of doing it.
As a measure of similarity between predicted spec and real spec, does PCC have a threshold to distort true positives and false positives?  For example, we will use the Andromeda score >100 as the threshold for MaxQuant identification in some cases.

If there is no such threshold yet, I may need to do some statistical testing to find a way out.

I would like to know whether the ProteomeTools data was used in the model training process corresponding to the` -i Lumos, -e 0.30 `parameter in the current version (model-180921). This determines whether I can use this type of data from ProteomeTools as my data set for statistical testing.

Thank you.

Zhang Le

**Comment by jalew188** [comment]
It depends, I think both PCC >= 0.9 or PCC >= 0.8 is OK. I recommend pValid to validate PSMs, it will be published soon.
