### ISSUE TITLE
Does this version include prediction of NH3 and H20 neutral loss ions?

### ISSUE THREAD

**Issue by cctsou** [pFindStudio/pDeep#2]
I saw in plabel files where neutral loss ions are included but I didn't see the prediction result for those ions. Are these ions considered in this version?

**Comment by jalew188** [comment]
@cctsou We currently only train the model to fit b/y and b/y-ModLoss (for example phos-98) ions. But I have reserved the apis to fit neutral loss.  If you need -H2O or -NH3 version, I can help you to train one.

**Comment by cctsou** [comment]
Yes, I have used your pDeep v1 to train model for our in-house data and it is working very well. Therefore I would also like to test how much improvement it could be by including -H2O or -NH3 ions. Looking forward to seeing if the v2 includes those ions.

**Comment by jalew188** [comment]
If you can train the model by yourself and you use pDeep src from pDeep/pDeep2 on github, it is quite easy to add neutral loss into the model:
In train.py, set the "ion_types = ['b{}', 'y{}', 'b{}-H2O', 'y{}-H2O']“, and then retrain the model to fit these four ion types.

**Comment by cctsou** [comment]
> If you can train the model by yourself and you use pDeep src from pDeep/pDeep2 on github, it is quite easy to add neutral loss into the model:
> In train.py, set the "ion_types = ['b{}', 'y{}', 'b{}-H2O', 'y{}-H2O']“, and then retrain the model to fit these four ion types.

Thanks a lot for the hint.

**Comment by jalew188** [comment]
@cctsou Hope it helps :)
