### ISSUE TITLE
Not able to use for ETD data

### ISSUE THREAD

**Issue by soninishant1990** [pFindStudio/pDeep#3]
Hi, I am not able to use pDeep for ETD data. pDeep only generating b and y ion. Can you please guide me on how I can generate c and z ion for ETD data.

**Comment by jalew188** [comment]
@soninishant1990 see issue #5

**Comment by jalew188** [comment]
@soninishant1990 We have uploaded a EThcD model onto https://github.com/pFindStudio/pDeep3. pDeep3 is the a new version of pDeep, Please check for its usage.
