### ISSUE TITLE
Predicting EThcD

### ISSUE THREAD

**Issue by lilianheil** [pFindStudio/pDeep#5]
Is there a pre-trained model for EThcD? When I set mod_config = fconfig.EThcD_Config() the predictions were the same as with HCD.

**Comment by jalew188** [comment]
@lilianheil We do not have ETD/EThcD models for pDeep2, hence setting mod_config does not work. Is there any simple EThcD dataset (containing a few raw files) except ProteomeTools?

**Comment by jalew188** [comment]
@lilianheil We have uploaded a EThcD model onto https://github.com/pFindStudio/pDeep3. pDeep3 is the a new version of pDeep, Please check for its usage.
